-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.lemonade
(
    sale_id serial NOT NULL,
    flavor character varying,
    size_type text,
    PRIMARY KEY (sale_id)
);

CREATE TABLE IF NOT EXISTS public.sale
(
    sale_id serial NOT NULL,
    day serial,
    size_sold numeric,
    total numeric,
    PRIMARY KEY (sale_id)
);

ALTER TABLE IF EXISTS public.sale
    ADD FOREIGN KEY (sale_id)
    REFERENCES public.lemonade (sale_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;