-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.lemonade
(
    lemonade_id serial NOT NULL,
    lemonade_size smallint,
    flavor_id smallint,
    lemonade_days date,
    PRIMARY KEY (lemonade_id)
);

CREATE TABLE IF NOT EXISTS public.lemonade_size
(
    lemonade_size_id serial NOT NULL,
    size text,
    sales money,
    PRIMARY KEY (lemonade_size_id)
);

CREATE TABLE IF NOT EXISTS public.flavor
(
    flavor_id serial NOT NULL,
    flavor text,
    lemonade_size_id integer,
    PRIMARY KEY (flavor_id)
);

ALTER TABLE IF EXISTS public.lemonade
    ADD FOREIGN KEY (lemonade_size)
    REFERENCES public.lemonade_size (lemonade_size_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lemonade
    ADD FOREIGN KEY (flavor_id)
    REFERENCES public.flavor (flavor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
/**
 * Ex. 12
 */
