/**
 * Ex. 11
 */
-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.lemonade
(
    lemonade_id serial NOT NULL,
    lemonade_size text,
    lemonade_price money,
    flavor_id integer,
    purchase_date date,
    number_drinks_purchased integer,
    PRIMARY KEY (lemonade_id)
);

CREATE TABLE IF NOT EXISTS public.flavor
(
    flavor_id serial NOT NULL,
    flavor_name text,
    PRIMARY KEY (flavor_id)
);

ALTER TABLE IF EXISTS public.lemonade
    ADD FOREIGN KEY (flavor_id)
    REFERENCES public.flavor (flavor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
/**
 * Ex. 12
 */
-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bank
(
    bank_id serial NOT NULL,
    bank_account text,
    account_balance money,
    date_opened date,
    date_closed date,
    PRIMARY KEY (bank_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    bank_id integer,
    first_name text,
    last_name text,
    username text,
    PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public.users
    ADD FOREIGN KEY (bank_id)
    REFERENCES public.bank (bank_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;