/**
 * Ex. 11
 */
BEGIN;


CREATE TABLE IF NOT EXISTS public.lemonade
(
    lemonade_id serial NOT NULL,
    lemonade_size text,
    price integer,
    flavor_id integer,
    purchase_date date,
    number_drinks integer,
    PRIMARY KEY (lemonade_id)
);

CREATE TABLE IF NOT EXISTS public.flavors
(
    flavor_id serial NOT NULL,
    flavor_name text,
    PRIMARY KEY (flavor_id)
);

ALTER TABLE IF EXISTS public.lemonade
    ADD FOREIGN KEY (flavor_id)
    REFERENCES public.flavors (flavor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
/**
 * Ex. 12
 */
 -- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."bank account"
(
    bank_account_id serial NOT NULL,
    bank_account integer,
    open_date date,
    close_date date,
    user_id integer,
    PRIMARY KEY (bank_account_id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    user_id serial NOT NULL,
    bank_account integer,
    first_name text,
    last_name text,
    username text,
    PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public."user"
    ADD FOREIGN KEY (bank_account)
    REFERENCES public."user" (bank_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."user"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."bank account" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;